Dear Anthony,

BWA HA HA HA!! I got your precious Princess Kaitlyn!
Since this ordeal is impossible to get through, I'll give you a couple of tips.

You walk RIGHT and LEFT with your keyboard's arrow keys.
Up and down arrow keys are JUMP and DUCK buttons respectively.
With the shift key, you can hold it to RUN while pressing the walking keys.
Also, shift allows you to THROW projectiles.

Oops! That's more than a couple! HA HA!
Anyway, come and try to get me like you do in Mario games, and
guess what? YOU WON'T!!! HA HA HA!!

Taylor McBowswell
------------------------------------------------
P.S. I hope not.